kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongo-volume-claim
spec:
  selector:
    matchLabels:
      for_app: mongo
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
