apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-volume
  namespace: headless-k
  labels:
    for_app: mongo
spec:
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/mongo-data"
